<?php

namespace CoreBundle\Repository;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends \Doctrine\ORM\EntityRepository
{


    public function getRecentJobs(){
        return $this->getQueryBuilder()->orderBy('j.updatedAt','desc')
            ->setMaxResults(10)->getQuery()->getResult();
    }

    public function searchForJob($keywords)
    {
        $keywords = explode(" ", $keywords);
        $qb = $this->getQueryBuilder();



        $condition = "CONCAT(j.location, j.position, j.company, c.name) LIKE :word";

        $qb->join('j.category','c')
            ->where($condition)
            ->setParameter('word', '%' . array_pop($keywords) . '%');


        foreach ($keywords as $keyword){
            $qb->orWhere($condition)->setParameter('word','%' . $keyword . '%');
        }

        return $qb->getQuery()->getResult();

    }



    private function getQueryBuilder()
    {
        $em = $this->getEntityManager();
        $qb = $em->getRepository('CoreBundle:Job')
            ->createQueryBuilder('j');
        return $qb;
    }

}
