<?php

namespace CoreBundle\Repository;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends \Doctrine\ORM\EntityRepository
{


    public function getRecentJobs(){
        return $this->getQueryBuilder()->orderBy('j.updatedAt','desc')
            ->setMaxResults(10)->getQuery()->getResult();
    }



    private function getQueryBuilder()
    {
        $em = $this->getEntityManager();
        $qb = $em->getRepository('CoreBundle:Job')
            ->createQueryBuilder('j');
        return $qb;
    }

}
